budgetapp/bills/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, DecimalField, DateField, BooleanField, SubmitField
from wtforms.validators import DataRequired, Length


class AddBillForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired(), Length(min=2, max=20)])
    amount = DecimalField('Amount')
    due = DateField('Due', validators=[DataRequired()])
    recurring = BooleanField('Recurring')
    fixed_amt = BooleanField('Fixed amount')
    frequency = SelectField('Frequency', choices=[('once', 'Once'), ('weekly', 'Weekly'), ('bi-weekly', 'Bi-Weekly'),
                                                  ('monthly', 'Monthly'), ('bi-monthly', 'Bi-Monthly'),
                                                  ('yearly', 'Yearly')])
    submit = SubmitField('Add')

budgetapp/bills/routes.py
from flask import Blueprint, render_template, flash, url_for, redirect, abort, request
from flask_login import login_required, current_user

from budgetapp import db, bills
from budgetapp.bills.forms import AddBillForm
from budgetapp.models import Bill, PastBills

bills = Blueprint('bills', __name__)


@bills.route("/bills")
@login_required
def bill_index():
    bills = Bill.query.filter_by(user=current_user).order_by(Bill.due)
    return render_template('bill_templates/index.html', title='Bills', bills=bills)


@bills.route("/add_bill/<string:category>", methods=['GET', 'POST'])
@login_required
def add_bill(category):
    form = AddBillForm()
    if category == "subscription" or category == "rentMortgage":
        recurring = True
        fixed_amt = True
    elif category == "utility" or category == "pmtPlan":
        recurring =True
        fixed_amt = form.fixed_amt.data
    else:
        recurring = form.recurring.data
        fixed_amt = form.fixed_amt.data
    if form.validate_on_submit():
        bill = Bill(name=form.name.data, amount=form.amount.data, fixed_amt=fixed_amt, due=form.due.data,
                    recurring=recurring, frequency=form.frequency.data, category=category,
                    user=current_user)
        db.session.add(bill)
        db.session.commit()
        flash('Bill Added successfully', 'success')
        return redirect(url_for('bills.bill_index'))
    return render_template('bill_templates/add_bill.html', title='Add Bill', form=form, category=category)


@bills.route("/bill/<int:bill_id>")
@login_required
def bill(bill_id):
    bill = Bill.query.get_or_404(bill_id)
    return render_template('bill_templates/bill.html', title=bill.id, bill=bill)


@bills.route("/bill/<int:bill_id>/delete", methods=['POST'])
@login_required
def delete_bill(bill_id):
    bill = Bill.query.get_or_404(bill_id)
    if bill.user_id != current_user.content_id:
        abort(403)
    db.session.delete(bill)
    db.session.commit()
    flash('Bill has been removed successfully', 'success')
    return redirect(url_for('bills.bill_index'))


@bills.route("/bill/<int:bill_id>/update", methods=['GET', 'POST'])
@login_required
def update_bill(bill_id):
    bill = Bill.query.get_or_404(bill_id)
    if bill.user_id != current_user.content_id:
        abort(403)
    form = AddBillForm()
    if form.validate_on_submit():
        bill.name = form.name.data
        bill.amount = form.amount.data
        bill.fixed_amt = form.fixed_amt.data
        bill.due = form.due.data
        bill.recurring = form.recurring.data
        bill.frequency = form.frequency.data
        db.session.commit()
        return redirect(url_for('bills.bill_index'))
    elif request.method == 'GET':
        form.name.data = bill.name
        form.amount.data = bill.amount
        form.fixed_amt.data = bill.fixed_amt
        form.due.data = bill.due
        form.recurring.data = bill.recurring
        form.frequency.data = bill.frequency
    return render_template('bill_templates/add_bill.html', title='Update Bill', form=form, legend='Update Bill')


@bills.route("/bill/<int:bill_id>/paid", methods=['GET', 'POST'])
@login_required
def paid(bill_id):
    frequency = {"once": 0, "weekly": 7, "bi-weekly": 14, "monthly": 1, "bi-monthly": 2, "yearly": 12}
    bill = Bill.query.get_or_404(bill_id)
    if bill.user_id != current_user.content_id:
        abort(403)
    past = PastBills(name=bill.name, amount=bill.amount, fixed_amt=bill.fixed_amt, due=bill.due,
                     recurring=bill.recurring, frequency=bill.frequency, category=bill.category,
                     user_id=current_user.id)
    if bill.recurring:
        adder = frequency.get(bill.frequency)
        if adder == 7 or adder == 14:
            bill.due = bill.due.replace(day=bill.due.day + adder)
        elif adder == 0:
            db.session.delete(bill)
        else:
            bill.due = bill.due.replace(month=bill.due.month + adder)
    else:
        db.session.delete(bill)
    db.session.add(past)
    db.session.commit()
    return redirect(url_for('bills.bill_index'))


@bills.route("/past_bills")
@login_required
def past_bills():
    bills = PastBills.query.filter_by(user_id=current_user.id).order_by(PastBills.due)
    return render_template('bill_templates/past_bills.html', title='Past Bills', bills=bills)


@bills.route("/bill/<int:bill_id>/delete_past_bill", methods=['POST'])
@login_required
def delete_past_bill(bill_id):
    bill = PastBills.query.get_or_404(bill_id)
    if bill.user_id != current_user.content_id:
        abort(403)
    db.session.delete(bill)
    db.session.commit()
    flash('Bill has been removed successfully', 'success')
    return redirect(url_for('bills.past_bills'))

budgetapp/templates/bill_templates/add_bill.html
{% extends 'app_layout.html' %}
{% block app_layout %}
<div class="container-fluid bills">
  <div class="card-header">
    <ul class="nav nav-tabs card-header-tabs">
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('bills.bill_index') }}">Bills</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link active dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
          Add Bill</a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="{{ url_for('bills.add_bill', category='subscription') }}">Subscription</a>
            <a class="dropdown-item" href="{{ url_for('bills.add_bill', category='rentMortgage') }}">Rent/Mortgage</a>
            <a class="dropdown-item" href="{{ url_for('bills.add_bill', category='utility') }}">Utility</a>
            <a class="dropdown-item" href="{{ url_for('bills.add_bill', category='pmtPlan') }}">Payment Plan</a>
            <a class="dropdown-item" href="{{ url_for('bills.add_bill', category='other') }}">Other</a>
          </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('bills.past_bills') }}">Past Bills</a>
      </li>
    </ul>
  </div>
</div>
  <div class="card-body bill-card-content">
    <form action="" method="post">
      {{ form.hidden_tag() }}
      <fieldset class="form-group">
          <legend class="border-bottom mb-4">Add Bill</legend>
          <div class="form-group">
            {{ form.name.label(class="form-control-label") }}
            {% if form.name.errors %}
              {{ form.name(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in form.name.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.name(class="form-control form-control-lg") }}
            {% endif %}
          </div>
          <div class="form-group">
            {{ form.amount.label(class="form-control-label") }}
            {% if form.amount.errors %}
              {{ form.amount(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in form.amount.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.amount(class="form-control form-control-lg") }}
            {% endif %}
          </div>
          <div class="form-group">
            {{ form.due.label(class="form-control-label") }}
            {% if form.due.errors %}
              {{ form.due(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in form.due.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.due(class="form-control form-control-lg", type="date") }}
            {% endif %}
          </div>
          {% if category == 'other' %}
          <div class="form-check" id="recurring">
              {{ form.recurring(class="form-check-input") }}
              {{ form.recurring.label(class="form-check-label") }}
          </div>
          {% endif %}
          {% if category != 'subscription' and category != 'rentMortgage' %}
          <div class="form-check" id="fixed_amt">
              {{ form.fixed_amt(class="form-check-input") }}
              {{ form.fixed_amt.label(class="form-check-label") }}
          </div>
          {% endif %}
          <div class="form-group" id="frequency">
              {{ form.frequency.label }}
              {{ form.frequency }}
          </div>
        </fieldset>
        <div class="form-group">
          {{ form.submit(class="btn btn-info")}}
        </div>
    </form>
  </div>
</div>
{% endblock app_layout %}

budgetapp/templates/bill_templates/bill.html
{% extends "app_layout.html" %}
{% block app_layout %}

{% endblock app_layout %}

budgetapp/templates/bill_templates/index.html
{% extends "app_layout.html" %}
{% block app_layout %}
<div class="container-fluid bills">
  <div class="card-header">
    <ul class="nav nav-tabs card-header-tabs">
      <li class="nav-item">
        <a class="nav-link active" href="{{ url_for('bills.bill_index') }}">Bills</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
          Add Bill</a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="{{ url_for('bills.add_bill', category='subscription') }}">Subscription</a>
            <a class="dropdown-item" href="{{ url_for('bills.add_bill', category='rentMortgage') }}">Rent/Mortgage</a>
            <a class="dropdown-item" href="{{ url_for('bills.add_bill', category='utility') }}">Utility</a>
            <a class="dropdown-item" href="{{ url_for('bills.add_bill', category='pmtPlan') }}">Payment Plan</a>
            <a class="dropdown-item" href="{{ url_for('bills.add_bill', category='other') }}">Other</a>
          </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('bills.past_bills') }}">Past Bills</a>
      </li>
    </ul>
  </div>
</div>
  <div class="card-body bill-card-content">
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Amount</th>
          <th scope="col">Due</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
     {% for bill in bills %}
      <tr>
        <td>{{ bill.name }}</td>
        <td>{{ bill.amount }}</td>
        <td>{{ bill.due.strftime('%d-%B-%Y') }}</td>
        <td>
          <form action="{{ url_for('bills.paid', bill_id=bill.id) }}" method="post">
            <input class="btn btn-secondary" type="submit" value="Paid">
          </form>
        </td>
        <td class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" name="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Edit</button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <form action="{{ url_for('bills.delete_bill', bill_id=bill.id) }}" method="post">
              <input class="dropdown-item" type ="submit" value="Delete">
            </form>
            <a class="dropdown-item" href="{{ url_for('bills.update_bill', bill_id=bill.id) }}">Update</a>
          </div>
        </td>
      </tr>
    {% endfor %}
    </table>
  </div>



{% endblock %}

budgetapp/templates/bill_templates/past_bills.html
{% extends "app_layout.html" %}
{% block app_layout %}
<div class="container-fluid bills">
  <div class="card-header">
    <ul class="nav nav-tabs card-header-tabs">
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('bills.bill_index') }}">Bills</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
          Add Bill</a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="{{ url_for('bills.add_bill', category='subscription') }}">Subscription</a>
            <a class="dropdown-item" href="{{ url_for('bills.add_bill', category='rentMortgage') }}">Rent/Mortgage</a>
            <a class="dropdown-item" href="{{ url_for('bills.add_bill', category='utility') }}">Utility</a>
            <a class="dropdown-item" href="{{ url_for('bills.add_bill', category='pmtPlan') }}">Payment Plan</a>
            <a class="dropdown-item" href="{{ url_for('bills.add_bill', category='other') }}">Other</a>
          </div>
      </li>
      <li class="nav-item">
        <a class="nav-link active" href="{{ url_for('bills.past_bills') }}">Past Bills</a>
      </li>
    </ul>
  </div>
</div>
  <div class="card-body bill-card-content">
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Amount</th>
          <th scope="col">Due</th>
        </tr>
      </thead>
     {% for bill in bills %}
      <tr>
        <td>{{ bill.name }}</td>
        <td>{{ bill.amount }}</td>
        <td>{{ bill.due.strftime('%d-%B-%Y') }}</td>
        <td>
          <form action="{{ url_for('bills.delete_past_bill', bill_id=bill.id) }}" method="post">
            <input class="btn btn-secondary" type ="submit" value="Remove">
        </form>
      </td>
    {% endfor %}
    </table>
  </div>



{% endblock %}