budgetapp/bills/routes.py
from flask import Blueprint, render_template, flash, url_for, redirect, abort, request
from flask_login import login_required, current_user

from budgetapp import db, bills
from budgetapp.bills.forms import AddBillForm
from budgetapp.models import Bill, PastBills

bills = Blueprint('bills', __name__)


@bills.route("/bills")
@login_required
def bill_index():
    bills = Bill.query.filter_by(user=current_user).order_by(Bill.due)
    return render_template('bill_templates/index.html', title='Bills', bills=bills)


@bills.route("/add_bill/<string:category>", methods=['GET', 'POST'])
@login_required
def add_bill(category):
    form = AddBillForm()
    if category == "subscription" or category == "rentMortgage":
        recurring = True
        fixed_amt = True
    elif category == "utility" or category == "pmtPlan":
        recurring =True
        fixed_amt = form.fixed_amt.data
    else:
        recurring = form.recurring.data
        fixed_amt = form.fixed_amt.data
    if form.validate_on_submit():
        bill = Bill(name=form.name.data, amount=form.amount.data, fixed_amt=fixed_amt, due=form.due.data,
                    recurring=recurring, frequency=form.frequency.data, category=category,
                    user=current_user)
        db.session.add(bill)
        db.session.commit()
        flash('Bill Added successfully', 'success')
        return redirect(url_for('bills.bill_index'))
    return render_template('bill_templates/add_bill.html', title='Add Bill', form=form, category=category)


@bills.route("/bill/<int:bill_id>")
@login_required
def bill(bill_id):
    bill = Bill.query.get_or_404(bill_id)
    return render_template('bill_templates/bill.html', title=bill.id, bill=bill)


@bills.route("/bill/<int:bill_id>/delete", methods=['POST'])
@login_required
def delete_bill(bill_id):
    bill = Bill.query.get_or_404(bill_id)
    if bill.user_id != current_user.content_id:
        abort(403)
    db.session.delete(bill)
    db.session.commit()
    flash('Bill has been removed successfully', 'success')
    return redirect(url_for('bills.bill_index'))


@bills.route("/bill/<int:bill_id>/update", methods=['GET', 'POST'])
@login_required
def update_bill(bill_id):
    bill = Bill.query.get_or_404(bill_id)
    if bill.user_id != current_user.content_id:
        abort(403)
    form = AddBillForm()
    if form.validate_on_submit():
        bill.name = form.name.data
        bill.amount = form.amount.data
        bill.fixed_amt = form.fixed_amt.data
        bill.due = form.due.data
        bill.recurring = form.recurring.data
        bill.frequency = form.frequency.data
        db.session.commit()
        return redirect(url_for('bills.bill_index'))
    elif request.method == 'GET':
        form.name.data = bill.name
        form.amount.data = bill.amount
        form.fixed_amt.data = bill.fixed_amt
        form.due.data = bill.due
        form.recurring.data = bill.recurring
        form.frequency.data = bill.frequency
    return render_template('bill_templates/add_bill.html', title='Update Bill', form=form, legend='Update Bill')


@bills.route("/bill/<int:bill_id>/paid", methods=['GET', 'POST'])
@login_required
def paid(bill_id):
    frequency = {"once": 0, "weekly": 7, "bi-weekly": 14, "monthly": 1, "bi-monthly": 2, "yearly": 12}
    bill = Bill.query.get_or_404(bill_id)
    if bill.user_id != current_user.content_id:
        abort(403)
    past = PastBills(name=bill.name, amount=bill.amount, fixed_amt=bill.fixed_amt, due=bill.due,
                     recurring=bill.recurring, frequency=bill.frequency, category=bill.category,
                     user_id=current_user.id)
    if bill.recurring:
        adder = frequency.get(bill.frequency)
        if adder == 7 or adder == 14:
            bill.due = bill.due.replace(day=bill.due.day + adder)
        elif adder == 0:
            db.session.delete(bill)
        else:
            bill.due = bill.due.replace(month=bill.due.month + adder)
    else:
        db.session.delete(bill)
    db.session.add(past)
    db.session.commit()
    return redirect(url_for('bills.bill_index'))


@bills.route("/past_bills")
@login_required
def past_bills():
    bills = PastBills.query.filter_by(user_id=current_user.id).order_by(PastBills.due)
    return render_template('bill_templates/past_bills.html', title='Past Bills', bills=bills)


@bills.route("/bill/<int:bill_id>/delete_past_bill", methods=['POST'])
@login_required
def delete_past_bill(bill_id):
    bill = PastBills.query.get_or_404(bill_id)
    if bill.user_id != current_user.content_id:
        abort(403)
    db.session.delete(bill)
    db.session.commit()
    flash('Bill has been removed successfully', 'success')
    return redirect(url_for('bills.past_bills'))

budgetapp/main/routes.py
import json

from flask import Blueprint, render_template, redirect
from flask_login import login_required, current_user
from flask_googlecharts import PieChart
from datetime import datetime

from budgetapp.main.methods import time_greeting, get_chart_labels, get_chart_values, \
    get_chart_colors, move_paid
from budgetapp.models import Bill
from budgetapp import charts

main = Blueprint('main', __name__)


@main.route("/")
def index():
    return render_template('index.html')


@main.route("/dashboard")
@login_required
def dashboard():
    move_paid()
    greeting = time_greeting()
    chart_labels = get_chart_labels()
    chart_values = get_chart_values()
    chart_colors = get_chart_colors()
    user = current_user.name
    bills = Bill.query.filter_by(user=current_user).order_by(Bill.due).limit(10)
    return render_template('dashboard.html', title='Dashboard', set=zip(chart_values, chart_labels, chart_colors),
                           greeting=greeting, user=user, bills=bills)


@main.route("/spendings")
@login_required
def spendings():
    return render_template('spendings.html', title='Spendings')

budgetapp/users/routes.py
from flask import Blueprint, url_for, flash, render_template, request, redirect
from flask_login import current_user, login_user, logout_user, login_required

from budgetapp import bcrypt, db
from budgetapp.models import User
from budgetapp.users.forms import RegistrationForm, LoginForm, RequestResetForm, ResetPasswordForm, AddUserForm, \
    UpdateAccountForm
from budgetapp.users.utils import send_reset_email, send_user_invite

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.dashboard'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(name=form.name.data, username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        user.content_id = user.id
        db.session.commit()
        flash('Account created successfully', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.dashboard'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.dashboard'))
        else:
            flash('Login Failed', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.index'))


@users.route("/password_reset", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.dashboard'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An Email has been sent', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/password_reset/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.dashboard'))
    user = User.verify_reset_token(token)
    if not user:
        flash('Token has expired', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Password updated successfully', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)


@users.route("/account_settings", methods=['GET', 'POST'])
@login_required
def account():
    update_account_form = UpdateAccountForm()
    add_user_form = AddUserForm()

    if update_account_form.validate_on_submit():
        current_user.name = update_account_form.name.data
        current_user.email = update_account_form.email.data
        current_user.password = update_account_form.password.data
        db.session.commit()
        flash('Your account has been updated', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        update_account_form.name.data = current_user.name
        update_account_form.email.data = current_user.email
        update_account_form.password.data = current_user.password

    if add_user_form.validate_on_submit():
        user = current_user
        email = add_user_form.email.data
        send_user_invite(user, email)
        flash('An invite has been sent', 'info')
        return redirect(url_for('users.account'))
    return render_template('account_settings.html', title='Account Settings', form=update_account_form,
                           add_user_form=add_user_form)


@users.route("/add_user", methods=['GET', 'POST'])
def add_user_request():
    form = AddUserForm()
    if form.validate_on_submit():
        user = current_user
        email = form.email.data
        send_user_invite(user, email)
        flash('An invite has been sent', 'info')
        return redirect(url_for('users.account'))
    return render_template('add_user.html', title='Add User', form=form)


@users.route("/add_user/<token>", methods=['GET', 'POST'])
def add_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.dashboard'))
    user = User.verify_add_token(token)
    if not user:
        flash('Token has expired', 'warning')
        return redirect(url_for('users.login'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        new_user = User(name=form.name.data, username=form.username.data, email=form.email.data,
                        password=hashed_password, content_id=user.content_id)
        db.session.add(new_user)
        db.session.commit()
        flash('Account created successfully', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Add Account', form=form)

budgetapp/templates/account_settings.html
{% extends "app_layout.html" %}
{% block app_layout %}
<div id="accordian">
  <div class="card">
    <div class="card-header" id="headingOne">
        <a class="card-link" data-toggle="collapse" href="#collapseOne">
          Edit Name, Email, Password
        </a>
    </div>
    <div id="collapseOne" class="collapse" data-parent="#accordian">
      <div class="card-body">
        <form action="" method="post" enctype="multipart/form-data">
          {{ form.hidden_tag() }}
          <fieldset class="form-group">
            <legend class="border-bottom mb-4">Update User Settings</legend>
            <div class="form-group">
              {{ form.name.label(class="form-control-label") }}
              {% if form.name.errors %}
                {{ form.name(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                  {% for error in form.name.errors %}
                    <span>{{ error }}</span>
                  {% endfor %}
                </div>
                {% else %}
                  {{ form.name(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
              {{ form.email.label(class="form-control-label") }}
              {% if form.email.errors %}
                {{form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                  {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                  {% endfor %}
                </div>
                {% else %}
                  {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
              {{ form.password.label(class="form-control-label") }}
              {% if form.password.errors %}
                {{ form.password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                  {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                  {% endfor %}
                </div>
              {% else %}
                {{ form.password(class="form-control form-control-lg") }}
              {% endif %}
            </div>
            <div class="form-group">
              {{ form.confirm_password.label(class="form-control-label") }}
              {% if form.confirm_password.errors %}
                {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                  {% for error in form.confirm_password.errors %}
                    <span>{{ error }}</span>
                  {% endfor %}
                </div>
              {% else %}
                {{ form.confirm_password(class="form-control form-control-lg") }}
              {% endif %}
            </div>
          </fieldset>
          <div class="form-group">
            {{ form.submit(class="btn btn-info") }}
          </div>
        </form>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header">
      <a class="card-link" data-toggle="collapse" href="#collapseTwo">
        Reminder Settings
      </a>
    </div>
    <div id="collapseTwo" class="collapse" data-parent="#accordian">
      <div class="card-body">
        Sorry this feature is not yet available. Please check back later.
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header">
      <a class="card-link" data-toggle="collapse" href="#collapseThree">
        Add another user to this account
      </a>
    </div>
    <div id="collapseThree" class="collapse" data-parent="#accordian">
      <div class="card-body">
        <form action="" method="post">
          {{ add_user_form.hidden_tag() }}
          <fieldset class="form-group">
            <legend class="border-bottom mb-4">Add User</legend>
            <div class="form-group">
              {{ add_user_form.email.label(class="form-control-label") }}
              {% if add_user_form.email.errors %}
                {{ add_user_form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                  {% for error in add_user_form.email.errors %}
                    <span>{{ error }}</span>
                  {% endfor %}
                </div>
              {% else %}
                {{ add_user_form.email(class="form-control form-control-lg") }}
              {% endif %}
            </div>
          </fieldset>
          <div class="form-group">
            {{ add_user_form.submit(class="btn btn-info") }}
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock app_layout %}

budgetapp/templates/add_user.html
{% extends 'app_layout.html' %}
{% block app_layout %}
<div class="container-fluid top-margin">
  <form action="" method="post">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Add User</legend>
      <div class="form-group">
        {{ form.email.label(class="form-control-label") }}
        {% if form.email.errors %}
          {{ form.email(class="form-control form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.email.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
          {{ form.email(class="form-control form-control-lg") }}
        {% endif %}
      </div>
    </fieldset>
    <div class="form-group">
      {{ form.submit(class="btn btn-info") }}
    </div>
  </form>
</div>
{% endblock app_layout %}

budgetapp/templates/app_layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name ="viewport" content ="width=device-width, initial-scale=1.0">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
   <link href="https://fonts.googleapis.com/css?family=Ubuntu&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/styles.css') }}">
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.min.js'></script>
    {% if title %}        <title>Budget App - {{ title }}</title>
    {% else %}
        <title>Budget App</title>
    {% endif %}
</head>
<body>
<nav class="navbar navbar-expand-sm navbar-dark">
  <a class="navbar-brand" href="{{ url_for('main.dashboard') }}">Budget Dashboard</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" name="button" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('bills.bill_index') }}">Bills</a>
      </li>
      {% if current_user.username == "admin" %}
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('main.spendings') }}">Spendings</a>
      </li>
      {% endif %}
      <div class="justify-content-end">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Account
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{{ url_for('users.account') }}">Settings</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{ url_for('users.logout') }}">logout</a>
          </div>
        </li>
      </div>
    </ul>
  </div>
</nav>
    <div class="container white-back">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
    </div>
    {% block app_layout %}{% endblock %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

budgetapp/templates/base_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name ="viewport" content ="width=device-width, initial-scale=1.0">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
   <link href="https://fonts.googleapis.com/css?family=Ubuntu&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/styles.css') }}">
    {% if title %}        <title>Budget App - {{ title }}</title>
    {% else %}
        <title>Budget App</title>
    {% endif %}
</head>
<body class="index-body">
    <div class="container white-back">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        {% block content %}{% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

budgetapp/templates/dashboard.html
{% extends 'app_layout.html' %}
{% block app_layout %}
<div class="container-fluid top-margin">
  <div class="row">
    <div class="col-md-8">
      <h2 class="center-text">{{ greeting }} {{ user }}</h2>
      <br>
      <h3>Expense Breakdown</h3>
      <canvas id="chart" width="600" height="400"></canvas>
      <script>
        var chartData = [
          {% for value, label, color in set %}
          {
            value: {{ value }},
            label: "{{ label }}",
            color: "{{ color }}"
          },
          {% endfor %}
        ];

        var billChart = document.getElementById("chart").getContext("2d");
        steps = 5

        new Chart(document.getElementById("chart").getContext("2d")).Pie(chartData);
      </script>
    </div>
    <div class="col-md-4">
      <ul class="list-group list-group-flush center-text">
        <h3>Upcoming Bills</h3>
      {% if bills.count() == 0 %}
        <h5>You currently have no upcoming bills to display</h5>
        <li class="list-group-item dropdown">
          <a class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
            Add Bill</a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="{{ url_for('bills.add_bill', category='subscription') }}">Subscription</a>
              <a class="dropdown-item" href="{{ url_for('bills.add_bill', category='rentMortgage') }}">Rent/Mortgage</a>
              <a class="dropdown-item" href="{{ url_for('bills.add_bill', category='utility') }}">Utility</a>
              <a class="dropdown-item" href="{{ url_for('bills.add_bill', category='pmtPlan') }}">Payment Plan</a>
              <a class="dropdown-item" href="{{ url_for('bills.add_bill', category='other') }}">Other</a>
            </div>
        </li>
      {% endif %}
      {% for bill in bills %}
        <li class="list-group-item">{{ bill }}</li>
      {% endfor %}
      {% if bills.count() > 0 %}
      <a href="{{ url_for('bills.bill_index') }}">View All</a>
      {% endif %}
      </ul>
    </div>
    </div>
  </div>
<!-- <script src="https://www.gstatic.com/charts/loader.js"></script>
<script src='{{ url_for('static', filename='scripts/dashboard.js') }}'></script> -->
{% endblock app_layout %}

budgetapp/templates/index.html
{% extends 'base_template.html' %}
{% block content %}
<body class="index-body">
<div class ="h-100 row align-items-center welcome">
    <div class="col">
        <h1 class="cover-heading">Welcome</h1>
        <p class="lead">Please login to continue to the budget app</p>
        <p class="lead">
            <a href="{{ url_for('users.login') }}" class="btn btn-lg btn-info btn-color">Login</a> <a href="{{ url_for('users.register') }}" class="btn btn-lg btn-info btn-color">Register</a>
        </p>
    </div>
</div>
</body>
{% endblock content %}

budgetapp/templates/login.html
{% extends 'base_template.html' %}
{% block content %}
    <div class="h-100 align-items-center welcome">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Sign In</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-info") }}
            </div>
            <small class="text-muted ml-2">
                <a href="{{ url_for('users.reset_request') }}">Forgot password?</a>
            </small>
        </form>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need an account? <a class="ml-2" href="{{ url_for('users.register') }}">Register</a>
        </small>
    </div>
  </div>
{% endblock content %}

budgetapp/templates/reset_request.html
{% extends 'base_template.html' %}
{% block content %}
<div class="h-100 align-items-center welcome">
  <form method="POST" action="">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Reset Password</legend>
      <div class="form-group">
        {{ form.email.label(class="form-control-label") }}
        {% if form.email.errors %}
          {{ form.email(class="form-control form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.email.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
          {% else %}
            {{ form.email(class="form-control form-control-lg") }}
          {% endif %}
      </div>
      </fieldset>
      <div class="form-group">
        {{ form.submit(class="btn btn-info") }}
      </div>
</div>
<div class="border-top pt-3">
    <small class="text-muted">
        Need an account? <a class="ml-2" href="{{ url_for('users.register') }}">Register</a>
    </small>
</div>
{% endblock content %}

budgetapp/templates/reset_token.html
{% extends 'base_template.html' %}
{% block content %}
<div class="content-section">
  <form method="POST" action="">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Reset Password</legend>
      <div class="form-group">
        {{ form.password.label(class="form-control-label") }}
        {% if form.password.errors %}
          {{ form.password(class="form-control form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.password.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
          {% else %}
            {{ form.password(class="form-control form-control-lg") }}
          {% endif %}
      </div>
      <div class="form-group">
        {{ form.confirm_password.label(class="form-control-label") }}
        {% if form.confirm_password.errors %}
          {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.confirm_password.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
          {% else %}
            {{ form.confirm_password(class="form-control form-control-lg") }}
          {% endif %}
      </div>
      <div class="form-group">
        {{ form.submit(class="btn btn-outline-info") }}
      </div>

    </fieldset>

</div>
{% endblock content %}

budgetapp/templates/spendings.html
{% extends 'app_layout.html' %}
{% block app_layout %}
{% endblock app_layout %}